import Knex from 'knex';

export async function seed(knex: Knex) {
    await knex('SubCategoriasDeProduto').insert([
       	{ nome: 'Frutas', idCategoriasDeProduto: '1'},
       	{ nome: 'Verduras', idCategoriasDeProduto: '1'},
       	{ nome: 'Cereais', idCategoriasDeProduto: '1'},
       	{ nome: 'Lanches', idCategoriasDeProduto: '1'},
       	{ nome: 'Biscoitos', idCategoriasDeProduto: '1'},
       	{ nome: 'Alimentos desnatado', idCategoriasDeProduto: '1'},
       	{ nome: 'Alimentos integral', idCategoriasDeProduto: '1'},
       	{ nome: 'Bolos', idCategoriasDeProduto: '2'},
       	{ nome: 'Brigadeiros', idCategoriasDeProduto: '2'},
       	{ nome: 'Donuts', idCategoriasDeProduto: '2'},
       	{ nome: 'Tortas', idCategoriasDeProduto: '2'},
       	{ nome: 'Cupcakes', idCategoriasDeProduto: '2'},
       	{ nome: 'Açaís', idCategoriasDeProduto: '3'},
       	{ nome: 'Casquinhas', idCategoriasDeProduto: '3'},
       	{ nome: 'Potes', idCategoriasDeProduto: '3'},
       	{ nome: 'Barcas', idCategoriasDeProduto: '3'},
       	{ nome: 'Aves', idCategoriasDeProduto: '4'},
       	{ nome: 'Bovinas', idCategoriasDeProduto: '4'},
       	{ nome: 'Suínas', idCategoriasDeProduto: '4'},
       	{ nome: 'Embutidos', idCategoriasDeProduto: '4'},
       	{ nome: 'Camisas', idCategoriasDeProduto: '5'},
       	{ nome: 'Calças', idCategoriasDeProduto: '5'},
       	{ nome: 'Shorts', idCategoriasDeProduto: '5'},
		{ nome: 'Saias', idCategoriasDeProduto: '5'},
		{ nome: 'Vestidos', idCategoriasDeProduto: '5'},
		{ nome: 'Bonés', idCategoriasDeProduto: '5'},
       	{ nome: 'Sandálias', idCategoriasDeProduto: '6'},
       	{ nome: 'Sapatos', idCategoriasDeProduto: '6'},
       	{ nome: 'Chuteiras', idCategoriasDeProduto: '6'},
       	{ nome: 'Tênis', idCategoriasDeProduto: '6'},
       	{ nome: 'Chinelos', idCategoriasDeProduto: '6'},
       	{ nome: 'Maquiagens', idCategoriasDeProduto: '7'},
       	{ nome: 'Cremes', idCategoriasDeProduto: '7'},
       	{ nome: 'Shampoos', idCategoriasDeProduto: '7'},
       	{ nome: 'Escovas', idCategoriasDeProduto: '7'},
       	{ nome: 'Aneis', idCategoriasDeProduto: '8'},
		{ nome: 'Alianças', idCategoriasDeProduto: '8'},
       	{ nome: 'Brincos', idCategoriasDeProduto: '8'},
       	{ nome: 'Relógios', idCategoriasDeProduto: '8'},
       	{ nome: 'Computadores', idCategoriasDeProduto: '9'},
       	{ nome: 'Celulares', idCategoriasDeProduto: '9'},
       	{ nome: 'Notebooks', idCategoriasDeProduto: '9'},
       	{ nome: 'Redes', idCategoriasDeProduto: '9'},
       	{ nome: 'Ferramentas', idCategoriasDeProduto: '9'},
    ])
}